config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :projects, except: [:show]
  get 'portfolio/:id', to: 'projects#show', as: 'project_show'

  get 'about', to: 'pages#about'
  get 'angular-items', to: 'projects#angular'
  get 'contact', to: 'pages#contact'
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  # setup for draft and pulbish modes.  From here on we can reference them as "draft" and "publish" rather than 0 and 1
  enum status: { draft: 0, published: 1 }

  # setup for friendly id slug urls
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.angular
    where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_project_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/models/skill.rb
# frozen_string_literal: true

class Skill < ApplicationRecord
  validates_presence_of :title, :percent_utilized
end

app/models/topic.rb
# frozen_string_literal: true

class Topic < ApplicationRecord
  validates_presence_of :title
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show; end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit; end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog is Live!' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index
    @project_items = Project.all
  end

  def angular
    @angular_project_items = Project.angular
  end

  def new
    @project_item = Project.new
  end

  def create
    @project_item = Project.new(params.require(:project).permit(:title, :subtitle, :body))

    respond_to do |format|
      if @project_item.save
        format.html { redirect_to projects_path, notice: 'Your project is now live' }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @project_item = Project.find(params[:id])
  end

  def edit
    @project_item = Project.find(params[:id])
  end

  def destroy
    # Perform the lookup
    @project_item = Project.find(params[:id])

    # Destroy/Delete the record
    @project_item.destroy

    # Redirect after the destroy
    respond_to do |format|
      format.html { redirect_to projects_path, notice: 'Project was successfully destroyed.' }
    end
  end

  def update
    @project_item = Project.find(params[:id])
    respond_to do |format|
      if @project_item.update(params.require(:project).permit(:title, :subtitle, :body))
        format.html { redirect_to projects_path, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Home Page</h1>
<br>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>
<%= link_to "Projects", projects_path  %>
<%= link_to "Blogs", blogs_path  %>

<h1>Blog Posts</h1>
<%= @posts.inspect %>

<h1>Skills</h1>
<%= @skills.inspect %>

app/views/projects/angular.html.erb
<h1>Angular Projects</h1>

<%= link_to "Create New Item", new_project_path %>

<% @angular_project_items.each do |project_item|%>
    <h3><%= link_to project_item.title, project_show_path(project_item) %></h3>
    <p><%= project_item.subtitle %></p>
    <p><%= project_item.body %></p>
    <%= image_tag project_item.thumb_image unless project_item.thumb_image.nil? %>
    <br>
    <%= link_to "Edit", edit_project_path(project_item) %>
    <%= link_to "Delete", project_path(project_item), method: :delete, data: { confirm: "Are you sure you want to delete #{project_item.title}?" } %>
    <hr>
<%end%>

app/views/projects/edit.html.erb
<h1>Edit your project</h1>

<%= form_for(@project_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>Portfolio</h1>

<%= link_to "Create New Item", new_project_path %>

<% @project_items.each do |project_item|%>
    <h3><%= link_to project_item.title, project_show_path(project_item) %></h3>
    <p><%= project_item.subtitle %></p>
    <p><%= project_item.body %></p>
    <%= image_tag project_item.thumb_image unless project_item.thumb_image.nil? %>
    <br>
    <%= link_to "Edit", edit_project_path(project_item) %>
    <%= link_to "Delete", project_path(project_item), method: :delete, data: { confirm: "Are you sure you want to delete #{project_item.title}?" } %>
    <hr>
<%end%>

app/views/projects/new.html.erb
<h1>Add a new project to your portfolio</h1>

<%= form_for(@project_item) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/show.html.erb
<h2><%= @project_item.title %></h2>
<em><%= @project_item.subtitle %></em>
<br>
<%= image_tag @project_item.main_image unless @project_item.thumb_image.nil? %>

<p><%= @project_item.body %></p>

<a href="/projects">Back</a>